### ISSUE TITLE
Clan event - only a portion of my XP is being calculated

### ISSUE THREAD

**Issue by ItsMeJess3** [wise-old-man/wise-old-man#1250] opened 2023-10-01 14:41 UTC
Hi team,

our clan event started at 10:00 PM MT on 9/30. 

I leveled up my thieving from about a level 36 to 56 from 10:00 PM 9/30 - 7:30ish PM 10/01 

the clan event shows I only went up three skill levels during that period of time - and my chart only shows I made progress starting at around 4:00 am MT 10:01 - what is going on? 

I leveled up to much more than what the clan event shows- is there anyway to check this? 

everyone else’s scores appear to be accurate.

my OSRS username is ItsMeJess3
My clan: Clan Generous 

Thanks,
Jess

**Comment by psikoi** [comment] 2023-10-01 14:59
- Competition started at 10 PM MT (September 30th)
- Your first "update" after the competition started wasn't until 5 AM MT (October 1st), which had you at `136,608` exp on the hiscores
- Your latest "update" has you at `194,803` exp on the hiscores.

This means you've only gained `58,195` since the competition started. And this is what the competition page says, this is correct.

---

Your "start" exp is the first update AFTER the competition starts, and your "end" exp is the last update BEFORE it ends.

**Comment by ItsMeJess3** [comment] 2023-10-01 15:28
So although I started gaining XP for this even when it started - you’re saying that because I had been singed in before it started, and didn’t sign out until 7am - 9 hours after it started, this sign out technically counted as the first update?

**Comment by ItsMeJess3** [comment] 2023-10-01 15:31
What I’m saying is - what causes an update? Is it signing out? Because I didn’t play more after signing out at 7 - so I don’t know why you’re seeing I’ve gained 58k XP - I believe the XP I was at when the event started should be my starting XP - which should show I gained a lot more than 58k XP

**Comment by psikoi** [comment] 2023-10-01 17:08
> What I’m saying is - what causes an update? Is it signing out?

When you logout, the hiscores update.

WOM uses the hiscores as the source of truth, so if the hiscores aren't yet updated (because you didn't logout), then we can't know what exp you have in-game. This is why we recommend ocompetition participants logout AND update themselves when the competition starts. So that their very first "update" within the competition, is accurate to their in-game exp.


Secondly, WOM doesn't just keep checking everyone's hiscores at all times, it needs to be told to check someone's hiscores, that's what an "update" is. It's the user telling WOM: "Hey, i've gained some exp since you've last seen me, please go check my hiscores and save the new stats"

There's a few ways you might be updated:

- Clicking the "Update" button on player profiles
- Clicking the "Update all" button on group profiles (only updates really outdated players, so not guaranteed to update you in particular)
- Using the /update command in our discord bot
- Using our API to request an update

And finally, WOM will try to update all players when the competition starts, but this is not guaranteed to be successful as it depends on peak times and the hiscores' behaving well, so it's advised to always baby-sit the beginning and ending of competitions to ensure participants were properly updated.

**Comment by psikoi** [comment] 2023-10-02 22:47
Working as intended, closing this.

**Closed by psikoi** 2023-10-02 22:47 UTC
