### ISSUE TITLE
Auto fetch competition start points

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#483] opened 2020-11-21 17:31 UTC
Suggestion:
Automatically fetch starting data points for all members at the beginning of a competition to ensure proper tracking. This fetch would bypass the 1h update cooldown so that everybody has a starting data point during the competition.

**Comment by psikoi** [comment] 2020-11-21 17:35
Duplicate of #126

**Closed by psikoi** 2020-11-21 17:35 UTC
