### ISSUE TITLE
Automatically update new users in active competition

### ISSUE THREAD

**Issue by steven10172** [wise-old-man/wise-old-man#818] opened 2021-06-15 07:52 UTC
Now that competitions automatically take a snapshot for all participants when it starts it should also have the ability to automatically snapshot a user that was added to a competition after it started if they don't have any existing data points within the competition timeframe.

**Comment by psikoi** [comment] 2021-06-15 10:25
Sounds good, similar/duplicate of #777

**Closed** 2021-08-11 18:03 UTC
