### ISSUE TITLE
Player type downgraded incorrectly 

### ISSUE THREAD

**Issue by GarethFunk** [wise-old-man/wise-old-man#704] opened 2021-03-12 23:14 UTC
I changed my name (eutecticman -> sank wok) and my player type was downgraded from UIM to IM.
When I try to "reassign player type" it comes back "confirmed as ironman" when my status is still UIM. 
I have gained XP as UIM since the name change. 
My rank has dropped accordingly because I'm now being ranked by IM ranks not UIM.

**Comment by psikoi** [comment] 2021-03-12 23:19
Hey, sorry about that, it was a typo in the code. Pushed a fix and it should be live in a few minutes. I'll keep this issue open until I can confirm it has been fixed.

**Comment by psikoi** [comment] 2021-03-12 23:26
Seems to be fixed, also deleted all your data that had the incorrect ranks. Closing now.

**Closed by psikoi** 2021-03-12 23:26 UTC
