### ISSUE TITLE
Invalid number error when creating group competitions

### ISSUE THREAD

**Issue by kgasiorowski** [wise-old-man/wise-old-man#1074] opened 2023-02-19 21:29 UTC
When provided valid params, the create competitions endpoint (`POST /competitions`) returns a 400 with 'Parameter groupId is not a valid number'.

Here's the data I used:
```
{
    "title": "Testing Competition",
    "metric": "agility",
    "startsAt": "2023-02-20T00:00:00.000000Z",
    "endsAt": "2023-02-27T10:00:00.000000Z",
    "groupId": 4236,
    "verificationCode": <valid verification code, redacted for security>
}
```
I've tried this endpoint both with my testing group and with the actual group, same error for both. Never had this problem before the v2 update.

**Comment by Jonxslays** [comment] 2023-02-19 22:19
The only way that error message should be triggered is if the group id isn't a number.
Are you sending this request via curl or what are you using to interact with the API?

I would make sure whatever you're using isn't converting the group id from a number to a string, it will fail if that is the case. I experienced this using the python aiohttp library.

Also note that `verificationCode` should be `groupVerificationCode`.

Here's a sample curl request i used and is working.

```sh
curl -X POST https://api.wiseoldman.net/v2/competitions \                                                              
 -H "Content-type: application/json" \
 -d '{ 
    "title": "Testing Competition",
    "metric": "agility",
    "startsAt": "2023-02-20T00:00:00.000000Z",
    "endsAt": "2023-02-27T10:00:00.000000Z",
    "groupId": 69,
    "groupVerificationCode": "111-111-111"
}'
```

[docs link](https://docs.wiseoldman.net/competitions-api/competition-endpoints#create-competition)  for ease of access.

**Comment by kgasiorowski** [comment] 2023-02-20 17:29
Yeah, sorry for the typo - it's `groupVerificationCode` in my code.

I'm using python's `requests` module to send out the post request. It's definitely a number and not a string when I send out the request. 

Here's the request object in my debugger, in the response from the API:

```
request = {PreparedRequest} <PreparedRequest [POST]>
 body = {str} 'title=Testing Competition&metric=agility&startsAt=2023-02-22T00%3A00%3A00.000000Z&endsAt=2023-03-01T00%3A00%3A00.000000Z&groupId=4236&groupVerificationCode=<redacted>'
 headers = {CaseInsensitiveDict: 6} {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '181', 'Content-Type': 'application/x-www-form-urlencoded'}
 hooks = {dict: 1} {'response': []}
 method = {str} 'POST'
 path_url = {str} '/v2/competitions'
 url = {str} 'https://api.wiseoldman.net/v2/competitions'
```

**Comment by Jonxslays** [comment] 2023-02-20 17:34
Can you provide exact reproduction code I can use? Omit the verification code string.
I have a strong suspicion requests is doing stuff behind the scenes.

**Comment by kgasiorowski** [comment] 2023-02-20 17:59
https://github.com/kgasiorowski/sotwBot/blob/master/api/WiseOldManApi.py#L7-L35

**Comment by psikoi** [comment] 2023-02-20 18:54
Duplicate of https://github.com/wise-old-man/wise-old-man/issues/971

**Closed by psikoi** 2023-02-20 18:54 UTC

**Comment by kgasiorowski** [comment] 2023-02-21 04:11
@Jonxslays Thanks very much for your help with this, appreciate it.
